name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - run: |
          npm install
      - run: |
          npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - uses: ./
        id: check-version
        with:
          working-directory: test

      - if: ${{ steps.check-version.outputs.version-formatted != '1.2.3' }}
        run: "echo 'Test failed. Expected 1.2.3, actual: ${{steps.check-version.outputs.version-formatted}}' && exit 1"
